<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 
<!-- Mirrored from www.py.cz/pipermail/python/2010-May/009781.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:18:38 GMT -->
<HEAD>
   <TITLE> [python] segfault error
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:python%40py.cz?Subject=Re%3A%20%5Bpython%5D%20segfault%20error&In-Reply-To=%3C48415044.20100518081935%40atlas.cz%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=iso-8859-2">
   <LINK REL="Previous"  HREF="http://www.py.cz/pipermail/python/2010-May/009780.html">
   <LINK REL="Next"  HREF="http://www.py.cz/pipermail/python/2010-May/009782.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[python] segfault error</H1>
    <B>mtip</B> 
    <A HREF="mailto:python%40py.cz?Subject=Re%3A%20%5Bpython%5D%20segfault%20error&In-Reply-To=%3C48415044.20100518081935%40atlas.cz%3E"
       TITLE="[python] segfault error">mtip na atlas.cz
       </A><BR>
    <I>Úterý Kvìten 18 08:19:35 CEST 2010</I>
    <P><UL>
        <LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2010-May/009780.html">[python] OT: preklad cookies
</A></li>
        <LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2010-May/009782.html">[python] segfault error
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2010-May/date.html#9781">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/thread.html#9781">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/subject.html#9781">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/author.html#9781">[ autora ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Zdravim vsechny,

mam script v pythonu pro server xmail na linuxu.
Tento script v rezimu ladeni, kdy je xmail spusten z konzole normalne funguje jak ma.
Ale  pokud  xmail  spustim  jako daemon, script se neprovede a jedine
co se da z logu vycist je radek ve /var/log/messages a to:
web kernel: python[9442]: segfault at bf9c52d0 ip b770e985 sp bf9c52d0 error 6 in libpython2.6.so.1.0[b763c000+139000]

Nevite nekdo, cim by to mohlo byt ?

Predem diky za odpovedi.

Mirek N.

</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2010-May/009780.html">[python] OT: preklad cookies
</A></li>
	<LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/python/2010-May/009782.html">[python] segfault error
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/python/2010-May/date.html#9781">[ data ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/thread.html#9781">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/subject.html#9781">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/python/2010-May/author.html#9781">[ autora ]</a>
         </LI>
       </UL>
<hr>
<a href="http://www.py.cz/mailman/listinfo/python">Dal¹í informace o konferenci Python</a><br>
</body>
<!-- Mirrored from www.py.cz/pipermail/python/2010-May/009781.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:18:38 GMT -->
</html>
