<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
 
<!-- Mirrored from www.py.cz/pipermail/tutor/2005-August/000059.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:36:12 GMT -->
<HEAD>
   <TITLE> [Tutor PyCZ] Kde najdu Exception arguments
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:tutor%40py.cz?Subject=%5BTutor%20PyCZ%5D%20Kde%20najdu%20Exception%20arguments&In-Reply-To=">
   <META NAME="robots" CONTENT="index,nofollow">
   <META http-equiv="Content-Type" content="text/html; charset=iso-8859-2">
   <LINK REL="Previous"  HREF="http://www.py.cz/pipermail/tutor/2005-August/000058.html">
   <LINK REL="Next"  HREF="http://www.py.cz/pipermail/tutor/2005-August/000060.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Tutor PyCZ] Kde najdu Exception arguments</H1>
    <B>Petr Prikryl</B> 
    <A HREF="mailto:tutor%40py.cz?Subject=%5BTutor%20PyCZ%5D%20Kde%20najdu%20Exception%20arguments&In-Reply-To="
       TITLE="[Tutor PyCZ] Kde najdu Exception arguments">PrikrylP na skil.cz
       </A><BR>
    <I>Pondìlí Srpen 15 09:17:37 CEST 2005</I>
    <P><UL>
        <LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/tutor/2005-August/000058.html">[Tutor PyCZ] Kde najdu Exception arguments
</A></li>
        <LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/tutor/2005-August/000060.html">[Tutor PyCZ] py2exe, nezakompilovani py souboru s konfiguraci
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/tutor/2005-August/date.html#59">[ data ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/thread.html#59">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/subject.html#59">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/author.html#59">[ autora ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>geon napsal...
&gt;<i> Oktavian Glider napsal
</I>&gt;<i> 
</I>&gt;<i> &gt; Potøebuji vìdìt jaký poèet argumentù mají 
</I>&gt;<i> &gt; jednotlivé exceptions. [...] Kde najdu nìjaký
</I>&gt;<i> &gt; seznam argumentù k jednotlivým exeptions? 
</I>&gt;<i> [...]
</I>&gt;<i> myslím, ¾e se to v¾dy pøedává jako tuple, 
</I>&gt;<i> jen nìkdy, èasto má tuple jen jeden prvek, 
</I>&gt;<i> tak¾e se automaticky pøiøazuje do promìnné
</I>&gt;<i> jako øetìzec. [...]
</I>
Standardní tøída Exceptions() mù¾e mít libovolný
poèet argumentù. Zále¾í na u¾ivateli, kolik jich
pou¾ije. 

Vnitønì se uchovávají v podobì n-tice (tuple, 
tedy pozdìji nemìnitelné struktury). Je pøístupná 
prostøednictvím atributu args. Pøíklad:

  &gt;&gt;&gt; e = Exception(1, 'ahoj', 3)
  &gt;&gt;&gt; e
  &lt;exceptions.Exception instance at 0x00925F80&gt;  
  &gt;&gt;&gt; e.args
  (1, 'ahoj', 3)
  &gt;&gt;&gt; type(e.args)
  &lt;type 'tuple'&gt;

Jejich konkrétní poèet mù¾u zjistit stejnì, 
jako zji¹»uji poèet prvkù n-tice:

  &gt;&gt;&gt; len(e.args)
  3

Indexováním mù¾eme zpøístupòovat jednotlivé
argumenty z args (jako u ka¾dé bì¾né n-tice).
  
  &gt;&gt;&gt; e.args[0]
  1
  &gt;&gt;&gt; e.args[1]
  'ahoj'
  &gt;&gt;&gt; e.args[2]
  3
  &gt;&gt;&gt; e.args[3]
  Traceback (most recent call last):
    File &quot;&lt;stdin&gt;&quot;, line 1, in ?
  IndexError: tuple index out of range

Proto¾e je definována metoda __getitem__(), 
mù¾eme argumenty zpøístupòovat i indexováním
samotného objektu:

  &gt;&gt;&gt; e[0]
  1
  &gt;&gt;&gt; e[1]
  'ahoj'
  &gt;&gt;&gt; e[2]
  3
  &gt;&gt;&gt; e[3]
  Traceback (most recent call last):
    File &quot;&lt;stdin&gt;&quot;, line 1, in ?
  IndexError: tuple index out of range

Metoda __str__() je definována tak, aby se 
zobrazila øetìzcová reprezentace argumentù.
Její výsledek typicky získáváme prostøednictvím
zabudované funkce str() nebo dosazením do pøíkazu
print:

  &gt;&gt;&gt; print e
  (1, 'ahoj', 3)
  &gt;&gt;&gt; str(e)
  &quot;(1, 'ahoj', 3)&quot;

S vý¹e uvedenými znalostmi bych mohl definovat
svou vlastní bázovou tøídu pro výjimky s podobnými
vlastnostmi takto:

  class MyException:
      &quot;&quot;&quot;Common base class for all MY exceptions.&quot;&quot;&quot;

      def __init__(self, *args):
          self.args = tuple(args)

      def __getitem__(self, i):
          return self.args[i]

      def __str__(self):
          return 'My exception: ' + str(self.args)

Standardní tøída Exceptions nemá pythonovský
zdrojový text, proto¾e je implementována pøímo
v jádøe jazyka, ale její definice by mohla 
vypadat témìø stejnì -- takto:

  class Exception:
      &quot;&quot;&quot;Common base class for all exceptions.&quot;&quot;&quot;

      def __init__(self, *args):
          self.args = tuple(args)

      def __getitem__(self, i):
          return self.args[i]

      def __str__(self):
          return str(self.args)

Vyvolání výjimky a její odchycení mù¾e v dokumentaci
vypadat trochu zmatenì, proto¾e se døíve výjimky 
realizovaly v podobì øetìzcových objektù. V souèasnosti
se mají v¾dy pou¾ívat výjimky odvozené od Exception.
Pøi vyvolávání výjimky si typicky objekt reprezentující
výjimku vytváøím -- doporuèuje se zápis vyjadøující
konstrukci nového objektu:


  try:
      ...
      raise Exception(1, 'ahoj', 3)
      ...

Pøi odchytávání výjimky se definuje pøedev¹ím
typ odchytávané výjimky (tj. typ objektu výjimky:

  except Exception:
      print 'Nastala vyjimka.'

Volitelnì mù¾eme uvést jméno, které bude spojeno 
s konkrétní instancí výjimky (s konkrétním objektem).
Jeho prostøednictvím si mù¾eme zpøístupnit argumenty
výjimky:

  except Exception, e:
      # e zpøístupòuje objekt výjimky.
      print e.args
      print e
      print len(e.args)
      for arg in e.args:
          print arg

... pøípadnì po zpracování argumentù mù¾eme 
výjimku znovu zápisem raise bez argumentù 
nebo, v na¹em pøípadì, zápisem &quot;raise e&quot;.
V druhém pøípadì mù¾u pøed opakovaným vyvoláním
výjimky pøiøadit do e.args novou n-tici, tak¾e
vlastnì mù¾u upøesnit nebo zcela zmìnit argumenty
výjimky. Systému je to jedno, ten se o argumenty
výjimky nestará. Je to èistì u¾ivatelská zále¾itost.

V¹echny ostatní formy zápisu (pokud se nepletu) jsou
dìdictvím minulosti a nedoporuèuje se je pou¾ívat.




pepr   
</PRE>


<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Pøedchozí pøíspìvek: <A HREF="http://www.py.cz/pipermail/tutor/2005-August/000058.html">[Tutor PyCZ] Kde najdu Exception arguments
</A></li>
	<LI>Následující pøíspìvek: <A HREF="http://www.py.cz/pipermail/tutor/2005-August/000060.html">[Tutor PyCZ] py2exe, nezakompilovani py souboru s konfiguraci
</A></li>
         <LI> <B>Zprávy tøídìné podle:</B> 
              <a href="http://www.py.cz/pipermail/tutor/2005-August/date.html#59">[ data ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/thread.html#59">[ vlákna ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/subject.html#59">[ subjektu ]</a>
              <a href="http://www.py.cz/pipermail/tutor/2005-August/author.html#59">[ autora ]</a>
         </LI>
       </UL>
<hr>
<a href="http://www.py.cz/mailman/listinfo/tutor">Dal¹í informace o konferenci Tutor</a><br>
</body>
<!-- Mirrored from www.py.cz/pipermail/tutor/2005-August/000059.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 20 Mar 2016 21:36:12 GMT -->
</html>
